services:
  p0:
    image: main:latest
    networks:
      - oram_test
    container_name: p0
    privileged: true
    entrypoint: ["/bin/sh", "-c", "echo 0 | tee /proc/sys/kernel/randomize_va_space && tc qdisc add dev eth0 root handle 1: htb default 12 && tc class add dev eth0 parent 1: classid 1:12 htb rate ${BANDWIDTH} && tc qdisc add dev eth0 parent 1:12 handle 10: netem delay ${LATENCY} && ./prac -p 0"]

  p1:
    image: main:latest
    networks:
      - oram_test
    container_name: p1
    privileged: true
    entrypoint: ["/bin/sh", "-c", "echo 0 | tee /proc/sys/kernel/randomize_va_space && tc qdisc add dev eth0 root handle 1: htb default 12 && tc class add dev eth0 parent 1: classid 1:12 htb rate ${BANDWIDTH} && tc qdisc add dev eth0 parent 1:12 handle 10: netem delay ${LATENCY} && ./prac -p 1 p0"]

  p2:
    image: main:latest
    networks:
      - oram_test
    container_name: p2
    privileged: true
    entrypoint: ["/bin/sh", "-c", "echo 0 | tee /proc/sys/kernel/randomize_va_space && tc qdisc add dev eth0 root handle 1: htb default 12 && tc class add dev eth0 parent 1: classid 1:12 htb rate ${BANDWIDTH} && tc qdisc add dev eth0 parent 1:12 handle 10: netem delay ${LATENCY}  && ./prac -p 2 p0 p1 r${DEPTH}:${PREPROC}"]

networks:
  oram_test:
    driver: bridge